### PR TITLE
Penny response in DMs

### PR DESCRIPTION
**Pull request by JelaniThompson**
Hey there!

I've gotten the desired effects for DMing Penny mentioned in Issue #5. Before I submit though, I just wanted to know if you had any suggestions for taking a more DRY approach or if you had a recommendation for a different approach altogether. I subbed out the channel ID of `#draw_it` for `message.channel` in the newly added block but other than that, most of the code is the same.

After this is done I'll start going over the possible things that Penny can reply to.

Pinging: @teesloane

### CODE REVIEW

**Comment by teesloane** [comment]
Hey hey!

Thanks for making a PR; so glad you're contributing @JelaniThompson !

So, I think you're onto something about trying to make this more DRY — we have two switch cases that are doing the same thing; we could probably have one. so I'm guessing there is a way to abstract that — perhaps in the `switch`es .

We have two checks for the channel (ie, is it a DM or is it in #draw-it)


```
// example check to see if the message is not in the channel but still @penny
message.text.includes(`<@${env.penny.id}>`) &&  message.channel != "C63GFH05V"
```

when perhaps the `checkMessage()` function could also do the same thing.

Feel free to think about it for a while, but I'm also happy to merge this by the end of the weekend to keep the project moving along ; after all we need this functionality regardless.

**Comment by JelaniThompson** [comment]
Hey @teesloane! 

Thanks, happy to be adding some features in. I added in ternary operators and got it down to one block as opposed to two (for the switches). Would you still prefer for all the channel checks to be done inside the `checkMessage()`?

**Comment by teesloane** [comment]
Awesome. I think this looks good.

`checkMessage()`'s goal is to check the substring of the mesage and then respond based on that, so I don't know if that's the best place for this logic. For now, if we look at your code, you are still repeating yourself 3 times, but it's much more dry than before. Arguable you could abstract that ternary into a function that takes possible other  functions to act on based on the result. I think for now that abstraction might be a little confusing and  unecessary; but you could always come back and refactor / change later

for now....

**Comment by JelaniThompson** [comment]
Sweet, thanks so much for merging and I'll keep the feedback in mind for when/if we find the need to revisit this code in particular. 👍

**Pull request merged**
